import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local';
import Navbar from "./components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sfProFont = localFont({
  src: '../../public/fonts/sfpro-regular.otf',
  variable: '--sf-pro', // Optional: for CSS variables
});

const shadowsIntoLightFont = localFont({
  src: '../../public/fonts/ShadowsIntoLight-Regular.ttf',
  variable: '--shadow-into-light', // Optional: for CSS variables
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${shadowsIntoLightFont.variable} ${sfProFont.className} `}>
      <body className={sfProFont.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
